- hosts: localhost
  vars_prompt:
    - name: "password"
      prompt: "Enter your password: "
      default: "local"
      private: yes
  tasks:
    - include_tasks: "{{ item}}"
      with_fileglob:
        - tasks/*.yml
